// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * GetTasks
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetTasks": () => {
        return window.go.main.App.GetTasks();
      },
      /**
       * StoreTask
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "StoreTask": (arg1) => {
        return window.go.main.App.StoreTask(arg1);
      },
    },
  },

};
export default go;
